### ISSUE TITLE
HCT a good choice?

### ISSUE THREAD

**Issue by vossi1** [schlae/snark-barker-mca#1]
Hello, this is not an issue, but a comment / question?

I built the plaidbib and it works perfectly with ALS and not with LS - like you recommended.

But for the snark barker you recommend HCT - but why? - HCT is slower than LS!
HC is slower than LS and HCT is even slower because of the TTL level adaption!

Timings from TI datasheets (load 45/50pF):
LS 245 has 8ns delay, 26ns enable, 15ns disable
HCT 245  15ns delay, 24ns enable, 24ns disable (at 5,0V)

I will use ALS 245 - like at the plaidbib - this is the best option and I think for all other chips is LS a good choice - better than slow HCTs.
I also tested successfully Fairchilds 74F245/04 in the plaidbib - very fast - but needs a lot of power.

**Comment by schlae** [comment]
fixed
