### ISSUE TITLE
DSP features

### ISSUE THREAD

**Issue by vossi1** [schlae/snark-barker-mca#2]
Hi, 
you wrote the SB 2.0 DSP has the best feature-set.
But what DSP features are missing if I use a 89s51 and program it with your hex?

From what Sb version is your disassembled DSP-firmware / hex-file?
Christian

**Comment by schlae** [comment]
several undocumented features, and the SBMIDI and ADPCM may not be 100% the same, as this firmware was dumped from a chinese SB clone. if it bothers you, consider using https://github.com/schlae/sb-firmware instead.
