### ISSUE TITLE
Faster machines

### ISSUE THREAD

**Issue by vossi1** [schlae/snark-barker-mca#3]
Hi, this is not an issue!

I just read that the original SB MCV was designed for 286 / 386 machines only. 
With faster machines it has problems with the bus and DMA.

You card runs in a 486/66 - so you built a much better SB MCA ;)
Has nobody tested it in a fast machine like a 9595 with P66 or P90 ?

The PlaidBib (without DMA) runs well in my P90 9595, I'm very curious if my Snark Barker MCA runs in my Server 95?
I have most critical chips as ALS here. But its a lot of work to build the card...

THANKS for designing this fantastic card!

**Comment by schlae** [comment]
Give it a try and let me know if you get it working so I can add it to the compatibility list. Make sure you use the updated ADF file, which I changed recently to fix a bug.

**Comment by vossi1** [comment]
Hi, first test in my 8570 with 16 MHz:
- FM works
- Digital sound works, also with DMA
- IRQ test OK
- joystick buttons ok
- MIDI Loop test ok
- Champ Kong, Shanghai 2 with digital sound ok
not good:
- Joystick analog input does not work, at first test there are zeros - I tried different NE558 - all are Signetics 1988 datecode - look original
- Microphone bar flickers full - no reaction of mic input visible - I tried different DAC0808 (china desoldered) - look original
- After some minutes testing or when simply copying files to hd, I get critical error when writing to harddisk from dos in the upper left corner!

Any hints for me?

**Comment by schlae** [comment]
Try swapping out U2 and U3. You could try a part from the AHCT family or the F family. The mic input requires a microphone that can provide its own bias voltage (for the electret type, it should have a battery inside it) or a dynamic mic that doesn't need a battery.

**Comment by vossi1** [comment]
Hi, 
the harddisk errors were cause by a chinese 74ALS245 fake (I think it's only a LS). With a real ALS no problems anymore.
The mic input error was easy to find: 390k instead of 39k soldered ;)
Swapping the 244 to a real old 74F244 doens't help with the joystick port. I ordered Philips NE558's - and hope that's the problem.
The card runs nice in my 9595 P90 !!!!! - I had to change my Etherlink resources IRQ 5 to 12 and address 200 to 600.
I just played duke 3D with sb+adlib music. The sound setup doesn't detects the adlib - but the game works with fm-sound.
Pinball Dreams 1 soundsetup crashes. I manually selected sblaster - but no sound in the game.

I use most ALS chips. Only the 74, 08 and 14 are LS types.

I will check more....

**Comment by vossi1** [comment]
Hello, the game port works now!
I first got five really good looking Signetics NE558 timers with datecode 8825VI from china.
I successfully tested them on a breadboard with a LED at the output and 100uF/10k for a 1 second pulse. 

Now I desoldered a Signetics 558 from an ESS audio drive ISA card and tested at also at the breadboard - it does exactly the same.
Finally I tested this 558 it in the snark barker mca - works perfectly.

So it seems that the chines built bad fakes that are partially working.
-> Be AWARE guys - these 558 from 88 are widely spreaded in the world offers at ebay, Aliexpress... !!!

Thanks again, TUBETIME, for the good work!

**Comment by schlae** [comment]
Great news! I've updated the readme with the information about the fake chips and the machines that you've tested your card in.

**Comment by mlyle** [comment]
@Vossi1 When you were having disk IO issues, what was that like?  I've opened #7 because of similar problems (many programs generate an NMI/exit, and then the hard disk doesn't work afterwards, and then the system fails POST with 00010300 until power cycled).

**Comment by vossi1** [comment]
> @vossi1 When you were having disk IO issues, what was that like? I've opened #7 because of similar problems (many programs generate an NMI/exit, and then the hard disk doesn't work afterwards, and then the system fails POST with 00010300 until power cycled).

As you read in my posts the harddisk problems were also present without the snark barker in the slot. Thats a SmartDrive problem with pcdos4.
