### ISSUE TITLE
Compability with 8580, especially 20MHz models

### ISSUE THREAD

**Issue by elosha** [schlae/snark-barker-mca#4]
1. The compability table contains a mistake, because -071 is a 16MHz model:
IBM PS/2 Model 80 | 8580-071 | 80386DX-**20** | Yes

2. Has anyone actually tested with 20MHz models (all except -0xx/-Axx)? Their planar is quite similar to 16MHz, but not identical. Maybe containing bugfixes, that allows use of a SB with Expansion Memory. Sadly, their planar only accepts 4MB of RAM directly, so those adapters are very common on these models.

3. What does "will behave erratically" in the 8580 notes mean exactly, what to expect?

**Comment by vossi1** [comment]
Hi, I have only a 8580-A31 with 2x4MB inside. But I haven't tested the SB in it till now.
I have some spare snark barker mca boards (located also in Germany), if you are interested...
search for vossi in the VzekC forum.

**Comment by schlae** [comment]
Turns out the 8580 machine I tested with does have the 16MHz planar after all. And it works fine. I've corrected the compatibility list.
